[package]
name = "agent_blackbox"
edition = "2024.beta"
license = "Apache-2.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

[addresses]
agent_blackbox = "0x0"
